Loading data into dataframe

In [1]:
!pip install pandas
!pip install nltk
!pip install matplotlib
!pip install scikit-learn

Requirement already satisfied: pandas in c:\users\cheta\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cheta\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cheta\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cheta\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cheta\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\cheta\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: nltk in c:\users\cheta\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\cheta\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\cheta\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\cheta\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\cheta\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\cheta\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: matplotlib in c:\users\cheta\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cheta\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\cheta\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: scikit-learn in c:\users\cheta\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\cheta\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\cheta\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\cheta\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\cheta\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [2]:
import numpy as np
import pandas as pd
from collections import Counter
import re
import string
import nltk
import matplotlib.pyplot as plt
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from itertools import compress
from nltk.stem import WordNetLemmatizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# Fetch dataset from Firebase instead of local CSV\nimport sys\nimport os\nif os.path.abspath('.') not in sys.path: sys.path.append(os.path.abspath('.'))\nfrom firebase_manager import fetch_dataframe_from_firebase\ntext = fetch_dataframe_from_firebase('reduced_reviews')

Sentiment Analysis

In [4]:
!pip install vaderSentiment

Requirement already satisfied: vaderSentiment in c:\users\cheta\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: requests in c:\users\cheta\anaconda3\lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\cheta\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\cheta\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\cheta\anaconda3\lib\site-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cheta\anaconda3\lib\site-packages (from requests->vaderSentiment) (2026.1.4)

Recommender

In [5]:
# Install SpaCy
!pip install spacy

# Download the medium English model
!python -m spacy download en_core_web_md

Requirement already satisfied: spacy in c:\users\cheta\anaconda3\lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (2.3.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\cheta\anaconda3\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\cheta\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\cheta\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\cheta\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\cheta\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\cheta\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\cheta\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\cheta\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\cheta\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\cheta\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\cheta\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.5.1)
Requirement already satisfied: httpx>=0.24.0 in c:\users\cheta\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in c:\users\cheta\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.10.0)
Requirement already satisfied: httpcore==1.* in c:\users\cheta\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\cheta\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\cheta\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\cheta\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\cheta\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in c:\users\cheta\anaconda3\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\cheta\anaconda3\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\cheta\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)
Collecting en-core-web-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.3/33.5 MB ? eta -:--:--
     -- ------------------------------------- 2.1/33.5 MB 6.9 MB/s eta 0:00:05
     ---- ----------------------------------- 3.4/33.5 MB 8.8 MB/s eta 0:00:04
     ---- ----------------------------------- 3.4/33.5 MB 8.8 MB/s eta 0:00:04
     ------ --------------------------------- 5.8/33.5 MB 6.2 MB/s eta 0:00:05
     ------- -------------------------------- 6.6/33.5 MB 5.8 MB/s eta 0:00:05
     -------- ------------------------------- 7.3/33.5 MB 5.6 MB/s eta 0:00:05
     ---------- ----------------------------- 8.9/33.5 MB 5.8 MB/s eta 0:00:05
     -------------- ------------------------- 12.1/33.5 MB 7.3 MB/s eta 0:00:03
     --------------- ------------------------ 12.8/33.5 MB 6.5 MB/s eta 0:00:04
     ------------------ --------------------- 15.2/33.5 MB 7.1 MB/s eta 0:00:03
     ------------------- -------------------- 16.5/33.5 MB 7.1 MB/s eta 0:00:03
     ---------------------- ----------------- 18.9/33.5 MB 7.3 MB/s eta 0:00:02
     -------------------------- ------------- 22.0/33.5 MB 7.9 MB/s eta 0:00:02
     ----------------------------- ---------- 24.4/33.5 MB 8.1 MB/s eta 0:00:02
     ------------------------------ --------- 25.4/33.5 MB 8.4 MB/s eta 0:00:01
     -------------------------------- ------- 27.5/33.5 MB 8.0 MB/s eta 0:00:01
     ----------------------------------- ---- 29.9/33.5 MB 8.3 MB/s eta 0:00:01
     ---------------------------------------  33.3/33.5 MB 8.8 MB/s eta 0:00:01
     ---------------------------------------- 33.5/33.5 MB 8.6 MB/s  0:00:04
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_md')

In [6]:
# Fetch dataset from Firebase instead of local CSV\nimport sys\nimport os\nif os.path.abspath('.') not in sys.path: sys.path.append(os.path.abspath('.'))\nfrom firebase_manager import fetch_dataframe_from_firebase\ntext = fetch_dataframe_from_firebase('reduced_reviews')

In [7]:
import spacy
nlp = spacy.load('en_core_web_md')

In [8]:
text['Simplified City'] = text['City'].apply(lambda x: re.sub(r"[^A-Za-z]+", ' ',x.lower()).split())

In [9]:
# Get city input
city=list()
City = input('Enter your preferred city. If no preference, just press Enter \n').lower()
city.append(City)

Enter your preferred city. If no preference, just press Enter
 jaipur

In [10]:
# Make dynamic after finishing code
# attr_list = ['park','fun','children']
attr_list = []
print('Enter what attribute you would want in your destination. Once you\'re done, just press Enter\n')
while 1:
    word = input().lower()
    if word!='':
        attr_list.append(word)
    else:
        break

attr_list

Enter what attribute you would want in your destination. Once you're done, just press Enter

 heritage

['heritage']

In [11]:
text['Review'] = text['Review'].fillna('')

In [12]:
text['Spacy Similarity'] = text['Review'].apply(lambda x: nlp(' '.join(attr_list)).similarity(nlp(x)))

In [ ]:
text.to_csv("C:/Users/cheta/Desktop/IDP-main/Processed_Review_db.csv")

In [13]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()
text['Sentiment'] = text['Review'].apply(lambda x: analyzer.polarity_scores(str(x))['compound'])

In [14]:
# Compound score
text['Spacy Similarity x Sentiment'] = text['Spacy Similarity'] * text['Sentiment']

In [15]:
agg_text = text.copy()
#agg_text = agg_text.drop(['Popular Mentions','Review','Words'], axis=1)
agg_text = agg_text.drop(['Raw_Review'], axis=1)
#aggregation_functions = {'Country': 'first','City': 'first','Description': 'first','Price': 'first', 'Rating':'mean','review_clean': 'sum', 'Sentiment score': 'mean','Spacy Similarity': 'mean','Spacy Similarity x Sentiment':'mean','Simplified Country':'first'}
aggregation_functions = {'City': 'first', 'Rating':'mean','Review': 'sum', 'Sentiment': 'mean','Spacy Similarity': 'mean','Spacy Similarity x Sentiment':'mean','Simplified City':'first'}
agg_text = agg_text.groupby(text['Place']).aggregate(aggregation_functions)
# agg_text = agg_text.sort_values(by='Spacy Similarity', ascending=False)
agg_text = agg_text.sort_values(by='Spacy Similarity x Sentiment', ascending=False)
agg_text['match']=round((agg_text['Spacy Similarity'] * 100), 2)
agg_text[:5]

,City,Rating,Review,Sentiment,Spacy Similarity,Spacy Similarity x Sentiment,Simplified City,match
Place,,,,,,,,
Vaikom Mahadeva Temple,Kottayam,5.0,visit temples like feel proud born india rich ...,0.9393,0.668640,0.628054,[kottayam],66.86
Ayyanar Horse Temple,Kanadukathan,5.0,visited tamil new year festival temple stands ...,0.9169,0.663414,0.608284,[kanadukathan],66.34
Ayya Vaikundar Nizhal Thangal,Kanyakumari,5.0,temple certain people come worship special imp...,0.8750,0.660917,0.578302,[kanyakumari],66.09
Fisherfolk Temple,Thalassery,5.0,promising believed locals thalassery people be...,0.8710,0.659859,0.574737,[thalassery],65.99
Bara Pathar Temple,Dalhousie,5.0,ancient temple enjoy view peaceful relaxing mi...,0.9246,0.610649,0.564606,[dalhousie],61.06

In [16]:
recommendations = pd.DataFrame()
recommendations.shape

(0, 0)

In [17]:
if city[0] != '':
    filt_text = agg_text[agg_text['Simplified City'].apply(lambda x: city[0] in x)]
else:
    filt_text = agg_text

In [18]:
print('Based on the attributes you\'ve entered, our top recommendation is', ''.join([i for i in filt_text.index[0] if (i.isalpha() or i.isspace())]))
print('Here are some details about',''.join([i for i in filt_text.index[0] if (i.isalpha() or i.isspace())]))
#print('Country: ',filt_text.iloc[0]['Country'])
print('City: ',filt_text.iloc[0]['City'])
top_city=filt_text.iloc[0]['City']
city.append(top_city)
#print('Description: ',filt_text.iloc[0]['Description'])
#print('Price: ',filt_text.iloc[0]['Price'])
print('Average Rating: ',filt_text.iloc[0]['Rating'])
print('% match: ',round(filt_text.iloc[0]['Spacy Similarity'] * 100, 2), '%')
#if review_desc.loc[filt_text.index[0], 'Similarity'] != 0:
 #   print('Here\'s how similar the reviews are to the official description ', round(review_desc.loc[filt_text.index[0], 'Similarity'] * 100, 2), '%')

Based on the attributes you've entered, our top recommendation is Ele Experience Farm
Here are some details about Ele Experience Farm
City:  Jaipur
Average Rating:  5.0
% match:  49.53 %

In [19]:
filt_text_city = agg_text[agg_text['City'].apply(lambda x: city[1] in x)]
filt_text_city

,City,Rating,Review,Sentiment,Spacy Similarity,Spacy Similarity x Sentiment,Simplified City,match
Place,,,,,,,,
Ele Experience Farm,Jaipur,5.000000,hello thanks words elephant farm pleasure host...,0.936000,0.495310,0.463610,[jaipur],49.53
Creative Fashion India,Jaipur,5.000000,say thought dealing reputable people anuj brot...,0.836000,0.505231,0.422373,[jaipur],50.52
Sawai Mansingh Stadium,Jaipur,5.000000,sawai man singh stadium good place players pla...,0.933700,0.448219,0.418502,[jaipur],44.82
Shila Devi Temple,Jaipur,5.000000,visiting amer fort make sure visit temple couy...,0.845150,0.486078,0.407228,[jaipur],48.61
Central Park,Jaipur,5.000000,mornings feels like heaven earth fresh air bir...,0.777150,0.521659,0.404719,[jaipur],52.17
Elephantwala,Jaipur,5.000000,time elephant ride super experience went cousi...,0.948500,0.422074,0.400338,[jaipur],42.21
Galtaji Temple,Jaipur,4.500000,woods outside jaipur beautiful religious compl...,0.781450,0.502977,0.398090,[jaipur],50.30
Jawahar Kala Kendra,Jaipur,5.000000,went night colleague govind family thousand ni...,0.848100,0.468799,0.397589,[jaipur],46.88
Elephant Joy,Jaipur,5.000000,came group elephant farm great experience feed...,0.875950,0.449020,0.395570,[jaipur],44.90
Kanak Vrindavan Gardens,Jaipur,5.000000,popularly known kanak ghati locals place reall...,0.884700,0.440152,0.389403,[jaipur],44.02
Gyan Museum,Jaipur,5.000000,dear visitor thank kind thoughtful feedback pl...,0.967800,0.383842,0.371482,[jaipur],38.38
Elephant Activity Planner,Jaipur,5.000000,visit elephant activity planner special highli...,0.916733,0.399975,0.367133,[jaipur],40.00
The Statue Circle,Jaipur,5.000000,nice walk dinner park prime clean good hawkers...,0.924450,0.388961,0.359724,[jaipur],38.90
Patrika Gate,Jaipur,5.000000,truly worth visit advice early morning beat cr...,0.884250,0.403798,0.356190,[jaipur],40.38
Jawahar Circle Garden,Jaipur,5.000000,jawahar circle perfect choice sunday outing at...,0.916900,0.374769,0.343625,[jaipur],37.48
B M Birla Auditorium,Jaipur,4.500000,auditorium big people facilities seats comfort...,0.684350,0.548596,0.341388,[jaipur],54.86
Ele Jaipur,Jaipur,5.000000,highlight trip fed elephants good staff kind e...,0.827100,0.410359,0.339408,[jaipur],41.04
Birla Mandir Temple,Jaipur,4.636364,visit temple times beautiful clean temple sile...,0.743318,0.453245,0.338011,[jaipur],45.32
Amer jeep Safari,Jaipur,4.777778,dear nameste amer jeep safari thanks kind revi...,0.855100,0.393879,0.336929,[jaipur],39.39
Sisodia Rani Palace and Garden,Jaipur,5.000000,sisodia rani palace garden beautiful place vis...,0.776950,0.428537,0.332878,[jaipur],42.85
Ram Niwas Garden,Jaipur,4.500000,area surrounding albert hall museum lively ver...,0.767200,0.434993,0.332164,[jaipur],43.50
Royal Gaitor Tumbas,Jaipur,5.000000,avid photographer stunning place amazing shots...,0.961800,0.344210,0.331061,[jaipur],34.42
Garh Ganesh Mandir,Jaipur,4.500000,garh ganesh temple wikipedia free encyclopedia...,0.741700,0.427609,0.318412,[jaipur],42.76
EleJaipur,Jaipur,5.000000,amazing experience ride elephant good price te...,0.908100,0.341279,0.309915,[jaipur],34.13
Triton Mall,Jaipur,5.000000,shops nice like room f pantaloons max parking ...,0.877900,0.342432,0.300621,[jaipur],34.24
"Khole Ke Hanuman JI Temple, Jaipur",Jaipur,4.333333,saw image went case location water lake infras...,0.676600,0.409917,0.285438,[jaipur],40.99
Govind Devji Temple,Jaipur,4.444444,visited recent tour jaipur despite different f...,0.612511,0.458743,0.284928,[jaipur],45.87
Man Sagar Lake,Jaipur,4.500000,better expected worth seeing lovely sun apart ...,0.667200,0.428549,0.278563,[jaipur],42.85
Jaigarh Fort,Jaipur,4.235294,jaigarh fort guarding fort amber fort located ...,0.583765,0.433629,0.269312,[jaipur],43.36
Ganesh Pol Gateway,Jaipur,4.000000,grand entrance forget hear sound main door mak...,0.624900,0.417388,0.260826,[jaipur],41.74
Jaivana,Jaipur,4.500000,apparently used place visit u r near amber for...,0.618400,0.427343,0.259906,[jaipur],42.73
Hawa Mahal - Palace of Wind,Jaipur,4.196970,best pink building situated market area sugges...,0.614176,0.402428,0.251406,[jaipur],40.24
Nahargarh Fort,Jaipur,4.333333,fort palace inside home maharani queens mahara...,0.598819,0.416395,0.251149,[jaipur],41.64
Jantar Mantar - Jaipur,Jaipur,4.209677,hats ancisters best place visit jaipur guide e...,0.578160,0.432554,0.251007,[jaipur],43.26
City Palace of Jaipur,Jaipur,4.204545,called palace nice antique items museum okay s...,0.585682,0.422394,0.250755,[jaipur],42.24
Albert Hall Museum,Jaipur,4.235294,like museum museum maintained popular tourist ...,0.571206,0.426153,0.246093,[jaipur],42.62
Jal Mahal,Jaipur,4.242424,revisited jal mahal better site visit parking ...,0.585582,0.407748,0.239979,[jaipur],40.77
Jaipur Wax Museum,Jaipur,4.400000,place visit time money worth spending location...,0.576000,0.423294,0.239058,[jaipur],42.33
Ayappa Temple,Jaipur,4.000000,good place visit family place shows kerala tou...,0.456800,0.511348,0.227317,[jaipur],51.13
Swargasuli Tower,Jaipur,4.000000,looks good night buy day enjoy view city climb...,0.564400,0.359619,0.214298,[jaipur],35.96
Panna Meena ka Kund,Jaipur,4.000000,bigger place great experience visit guide told...,0.532900,0.387712,0.205556,[jaipur],38.77
Diwan-e-Khas Hall of Private Audience,Jaipur,4.000000,located inside amber fort exquisite craftmansh...,0.385850,0.460166,0.200283,[jaipur],46.02
Jaipur Zoo,Jaipur,3.500000,kept hardly stink like visited lot blackbucks ...,0.326700,0.407054,0.144115,[jaipur],40.71
Maharaja Sawai Man Singh II Museum,Jaipur,3.000000,enthusiastic old world relics stories place mi...,0.250000,0.525011,0.131253,[jaipur],52.50
Anokhi Museum of Hand Printing,Jaipur,3.500000,trip advisor said open monday hired driver hou...,0.292450,0.423868,0.128441,[jaipur],42.39
Brihaspati Dham Mandir,Jaipur,3.000000,new temple brihaspati deity connected jupiter ...,0.250000,0.454392,0.113598,[jaipur],45.44
Moti Dungari Temple,Jaipur,3.000000,temple story famous moti dungari ganesh temple...,0.000000,0.600530,0.000000,[jaipur],60.05
Mukesh Art Gallery,Jaipur,3.000000,visited place price paintings high purchased y...,0.000000,0.309505,0.000000,[jaipur],30.95

In [20]:
def similar_places(df):

  if(len(df)==1):
    print('Sorry... There are no other places matching the description in the vicinity\n')
  elif(3>len(df)):
    print('Here are some similar spots worth checking out in your vicinity\n')
    return filt_text_city[1:len(df)]
  else:
    print('Here are some similar spots worth checking out in your vicinity\n')
    return filt_text_city[1:6]

In [21]:
similar_places(filt_text_city)

Here are some similar spots worth checking out in your vicinity

,City,Rating,Review,Sentiment,Spacy Similarity,Spacy Similarity x Sentiment,Simplified City,match
Place,,,,,,,,
Creative Fashion India,Jaipur,5.0,say thought dealing reputable people anuj brot...,0.83600,0.505231,0.422373,[jaipur],50.52
Sawai Mansingh Stadium,Jaipur,5.0,sawai man singh stadium good place players pla...,0.93370,0.448219,0.418502,[jaipur],44.82
Shila Devi Temple,Jaipur,5.0,visiting amer fort make sure visit temple couy...,0.84515,0.486078,0.407228,[jaipur],48.61
Central Park,Jaipur,5.0,mornings feels like heaven earth fresh air bir...,0.77715,0.521659,0.404719,[jaipur],52.17
Elephantwala,Jaipur,5.0,time elephant ride super experience went cousi...,0.94850,0.422074,0.400338,[jaipur],42.21

In [22]:
print('Our next recommendation is', ''.join([i for i in filt_text.index[1] if (i.isalpha() or i.isspace())]))
print('Here are some details about',''.join([i for i in filt_text.index[1] if (i.isalpha() or i.isspace())]))
#print('Country: ',filt_text.iloc[1]['Country'])
print('City: ',filt_text.iloc[1]['City'])
top_city = filt_text.iloc[1]['City']
city.append(top_city)
#print('Description: ',filt_text.iloc[1]['Description'])
#print('Price: ',filt_text.iloc[1]['Price'])
print('Average Rating: ',filt_text.iloc[1]['Rating'])
print('% match: ',round(filt_text.iloc[1]['Spacy Similarity'] * 100, 2), '%')
#if review_desc.loc[filt_text.index[1], 'Similarity'] != 0:
#    print('Here\'s how similar the reviews are to the official description ', round(review_desc.loc[filt_text.index[1], 'Similarity'] * 100,2), '%')

Our next recommendation is Creative Fashion India
Here are some details about Creative Fashion India
City:  Jaipur
Average Rating:  5.0
% match:  50.52 %

In [23]:
filt_text_city = agg_text[agg_text['City'].apply(lambda x: city[2] in x)]
filt_text_city

,City,Rating,Review,Sentiment,Spacy Similarity,Spacy Similarity x Sentiment,Simplified City,match
Place,,,,,,,,
Ele Experience Farm,Jaipur,5.000000,hello thanks words elephant farm pleasure host...,0.936000,0.495310,0.463610,[jaipur],49.53
Creative Fashion India,Jaipur,5.000000,say thought dealing reputable people anuj brot...,0.836000,0.505231,0.422373,[jaipur],50.52
Sawai Mansingh Stadium,Jaipur,5.000000,sawai man singh stadium good place players pla...,0.933700,0.448219,0.418502,[jaipur],44.82
Shila Devi Temple,Jaipur,5.000000,visiting amer fort make sure visit temple couy...,0.845150,0.486078,0.407228,[jaipur],48.61
Central Park,Jaipur,5.000000,mornings feels like heaven earth fresh air bir...,0.777150,0.521659,0.404719,[jaipur],52.17
Elephantwala,Jaipur,5.000000,time elephant ride super experience went cousi...,0.948500,0.422074,0.400338,[jaipur],42.21
Galtaji Temple,Jaipur,4.500000,woods outside jaipur beautiful religious compl...,0.781450,0.502977,0.398090,[jaipur],50.30
Jawahar Kala Kendra,Jaipur,5.000000,went night colleague govind family thousand ni...,0.848100,0.468799,0.397589,[jaipur],46.88
Elephant Joy,Jaipur,5.000000,came group elephant farm great experience feed...,0.875950,0.449020,0.395570,[jaipur],44.90
Kanak Vrindavan Gardens,Jaipur,5.000000,popularly known kanak ghati locals place reall...,0.884700,0.440152,0.389403,[jaipur],44.02
Gyan Museum,Jaipur,5.000000,dear visitor thank kind thoughtful feedback pl...,0.967800,0.383842,0.371482,[jaipur],38.38
Elephant Activity Planner,Jaipur,5.000000,visit elephant activity planner special highli...,0.916733,0.399975,0.367133,[jaipur],40.00
The Statue Circle,Jaipur,5.000000,nice walk dinner park prime clean good hawkers...,0.924450,0.388961,0.359724,[jaipur],38.90
Patrika Gate,Jaipur,5.000000,truly worth visit advice early morning beat cr...,0.884250,0.403798,0.356190,[jaipur],40.38
Jawahar Circle Garden,Jaipur,5.000000,jawahar circle perfect choice sunday outing at...,0.916900,0.374769,0.343625,[jaipur],37.48
B M Birla Auditorium,Jaipur,4.500000,auditorium big people facilities seats comfort...,0.684350,0.548596,0.341388,[jaipur],54.86
Ele Jaipur,Jaipur,5.000000,highlight trip fed elephants good staff kind e...,0.827100,0.410359,0.339408,[jaipur],41.04
Birla Mandir Temple,Jaipur,4.636364,visit temple times beautiful clean temple sile...,0.743318,0.453245,0.338011,[jaipur],45.32
Amer jeep Safari,Jaipur,4.777778,dear nameste amer jeep safari thanks kind revi...,0.855100,0.393879,0.336929,[jaipur],39.39
Sisodia Rani Palace and Garden,Jaipur,5.000000,sisodia rani palace garden beautiful place vis...,0.776950,0.428537,0.332878,[jaipur],42.85
Ram Niwas Garden,Jaipur,4.500000,area surrounding albert hall museum lively ver...,0.767200,0.434993,0.332164,[jaipur],43.50
Royal Gaitor Tumbas,Jaipur,5.000000,avid photographer stunning place amazing shots...,0.961800,0.344210,0.331061,[jaipur],34.42
Garh Ganesh Mandir,Jaipur,4.500000,garh ganesh temple wikipedia free encyclopedia...,0.741700,0.427609,0.318412,[jaipur],42.76
EleJaipur,Jaipur,5.000000,amazing experience ride elephant good price te...,0.908100,0.341279,0.309915,[jaipur],34.13
Triton Mall,Jaipur,5.000000,shops nice like room f pantaloons max parking ...,0.877900,0.342432,0.300621,[jaipur],34.24
"Khole Ke Hanuman JI Temple, Jaipur",Jaipur,4.333333,saw image went case location water lake infras...,0.676600,0.409917,0.285438,[jaipur],40.99
Govind Devji Temple,Jaipur,4.444444,visited recent tour jaipur despite different f...,0.612511,0.458743,0.284928,[jaipur],45.87
Man Sagar Lake,Jaipur,4.500000,better expected worth seeing lovely sun apart ...,0.667200,0.428549,0.278563,[jaipur],42.85
Jaigarh Fort,Jaipur,4.235294,jaigarh fort guarding fort amber fort located ...,0.583765,0.433629,0.269312,[jaipur],43.36
Ganesh Pol Gateway,Jaipur,4.000000,grand entrance forget hear sound main door mak...,0.624900,0.417388,0.260826,[jaipur],41.74
Jaivana,Jaipur,4.500000,apparently used place visit u r near amber for...,0.618400,0.427343,0.259906,[jaipur],42.73
Hawa Mahal - Palace of Wind,Jaipur,4.196970,best pink building situated market area sugges...,0.614176,0.402428,0.251406,[jaipur],40.24
Nahargarh Fort,Jaipur,4.333333,fort palace inside home maharani queens mahara...,0.598819,0.416395,0.251149,[jaipur],41.64
Jantar Mantar - Jaipur,Jaipur,4.209677,hats ancisters best place visit jaipur guide e...,0.578160,0.432554,0.251007,[jaipur],43.26
City Palace of Jaipur,Jaipur,4.204545,called palace nice antique items museum okay s...,0.585682,0.422394,0.250755,[jaipur],42.24
Albert Hall Museum,Jaipur,4.235294,like museum museum maintained popular tourist ...,0.571206,0.426153,0.246093,[jaipur],42.62
Jal Mahal,Jaipur,4.242424,revisited jal mahal better site visit parking ...,0.585582,0.407748,0.239979,[jaipur],40.77
Jaipur Wax Museum,Jaipur,4.400000,place visit time money worth spending location...,0.576000,0.423294,0.239058,[jaipur],42.33
Ayappa Temple,Jaipur,4.000000,good place visit family place shows kerala tou...,0.456800,0.511348,0.227317,[jaipur],51.13
Swargasuli Tower,Jaipur,4.000000,looks good night buy day enjoy view city climb...,0.564400,0.359619,0.214298,[jaipur],35.96
Panna Meena ka Kund,Jaipur,4.000000,bigger place great experience visit guide told...,0.532900,0.387712,0.205556,[jaipur],38.77
Diwan-e-Khas Hall of Private Audience,Jaipur,4.000000,located inside amber fort exquisite craftmansh...,0.385850,0.460166,0.200283,[jaipur],46.02
Jaipur Zoo,Jaipur,3.500000,kept hardly stink like visited lot blackbucks ...,0.326700,0.407054,0.144115,[jaipur],40.71
Maharaja Sawai Man Singh II Museum,Jaipur,3.000000,enthusiastic old world relics stories place mi...,0.250000,0.525011,0.131253,[jaipur],52.50
Anokhi Museum of Hand Printing,Jaipur,3.500000,trip advisor said open monday hired driver hou...,0.292450,0.423868,0.128441,[jaipur],42.39
Brihaspati Dham Mandir,Jaipur,3.000000,new temple brihaspati deity connected jupiter ...,0.250000,0.454392,0.113598,[jaipur],45.44
Moti Dungari Temple,Jaipur,3.000000,temple story famous moti dungari ganesh temple...,0.000000,0.600530,0.000000,[jaipur],60.05
Mukesh Art Gallery,Jaipur,3.000000,visited place price paintings high purchased y...,0.000000,0.309505,0.000000,[jaipur],30.95

In [24]:
result=similar_places(filt_text_city)
result

Here are some similar spots worth checking out in your vicinity

,City,Rating,Review,Sentiment,Spacy Similarity,Spacy Similarity x Sentiment,Simplified City,match
Place,,,,,,,,
Creative Fashion India,Jaipur,5.0,say thought dealing reputable people anuj brot...,0.83600,0.505231,0.422373,[jaipur],50.52
Sawai Mansingh Stadium,Jaipur,5.0,sawai man singh stadium good place players pla...,0.93370,0.448219,0.418502,[jaipur],44.82
Shila Devi Temple,Jaipur,5.0,visiting amer fort make sure visit temple couy...,0.84515,0.486078,0.407228,[jaipur],48.61
Central Park,Jaipur,5.0,mornings feels like heaven earth fresh air bir...,0.77715,0.521659,0.404719,[jaipur],52.17
Elephantwala,Jaipur,5.0,time elephant ride super experience went cousi...,0.94850,0.422074,0.400338,[jaipur],42.21

itinerary generator

In [33]:
from google import genai
import pandas as pd

# --- Phase 1: Authentication and Model Initialization ---
# The modern SDK utilizes a Client instantiation rather than global configuration.
# Insert your NEW, secure API key here.
import os
from dotenv import load_dotenv
load_dotenv()
client = genai.Client(api_key=os.environ.get('GOOGLE_API_KEY'))

# --- Phase 2: Data Extraction and Validation ---

# SAFE RESET: Only reset the index if 'Place' isn't already a column.
# This stops the notebook from crashing if you run this cell multiple times!
if 'Place' not in filt_text_city.columns:
    filt_text_city = filt_text_city.reset_index()

# Isolate the primary recommendation (index 0).
result = filt_text_city.iloc[0]

chosen_place = result['Place']
chosen_city = result['City']

print(f"Algorithmically Selected Destination: {chosen_place} situated in {chosen_city}")

# --- Phase 3: Parameter Ingestion ---
# Note: The hardcoded DataFrame containing Mumbai/Delhi/Goa has been permanently excised
# to preserve the integrity of your NLP recommendation engine.
num_days = int(input(f"Please enter the intended duration for the {chosen_place} expedition (in days): "))

# --- Phase 4: Financial Estimation Module ---
def get_price_estimate(client, place, city):
    """Queries the LLM for a generalized financial estimation."""
    prompt = f"Provide a concise financial estimate for a visit to {place} in {city}, accounting for entry fees and primary activities."
    
    # Modern SDK execution protocol
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt
    )
    return response.text

print(f"\nProcessing financial estimations for {chosen_place}...")
estimated_price = get_price_estimate(client, chosen_place, chosen_city)
print(f"Financial Projection:\n{estimated_price}")

# --- Phase 5: Itinerary Generation Module ---
def generate_itinerary(client, place, city, days, estimated_price):
    """Synthesizes a structured itinerary based on temporal and geographic parameters."""
    prompt = (
        f"Act as a professional logistical coordinator. "
        f"Formulate a structured {days}-day itinerary for a field expedition to {place} located in {city}. "
        f"Integrate the primary activities, strategic time allocations, and accommodate a financial parameter of: {estimated_price}."
    )
    
    # Modern SDK execution protocol
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt
    )
    return response.text

print("\nSynthesizing the chronological itinerary framework...")
itinerary = generate_itinerary(client, chosen_place, chosen_city, num_days, estimated_price)

print("\n--- Finalized Itinerary ---")
print(itinerary)

Algorithmically Selected Destination: Ele Experience Farm situated in Jaipur

Please enter the intended duration for the Ele Experience Farm expedition (in days):  2

Processing financial estimations for Ele Experience Farm...
Financial Projection:
A visit to Ele Experience Farm, including entry and primary activities like elephant feeding, bathing, and interaction, typically costs **INR 2,500 - 4,000 per person**. This estimate excludes transport and personal expenses.

Synthesizing the chronological itinerary framework...

--- Finalized Itinerary ---
Okay, as your dedicated logistical coordinator, I have formulated a comprehensive and structured 2-day itinerary for your expedition to Ele Experience Farm in Jaipur. This plan focuses on optimal engagement with the primary activity while strategically integrating other key Jaipur highlights to maximize your experience within the specified financial parameters and logistical considerations.

---

**Expedition Title:** Ele Experience & Jaipur Cultural Immersion
**Duration:** 2 Days / 1 Night
**Destination:** Ele Experience Farm, Jaipur & Jaipur City
**Primary Focus:** Ethical Elephant Interaction and Jaipur Heritage Exploration

---

### **Logistical Overview & Key Considerations:**

*   **Accommodation:** Not included in the Ele Experience Farm cost. It is recommended to book a hotel in Jaipur city (e.g., near Amber Fort area for convenience to the farm, or central Jaipur for city exploration) for overnight stay.
*   **Transportation:** Not included in the Ele Experience Farm cost. A private air-conditioned car with a driver for the entire 2 days is highly recommended for comfort and efficiency, given Jaipur's spread-out attractions. Alternatively, ride-sharing apps (Uber/Ola) can be used, but may be less reliable for continuous service outside the main city.
*   **Meals:** Not included. Budget for breakfast, lunch, and dinner.
*   **Booking:** It is **imperative** to book your slot at Ele Experience Farm in advance, especially during peak season, to ensure availability and confirm their operating hours for the desired activities. Similarly, pre-booking your transport is advised.
*   **Attire:** Comfortable, loose-fitting clothing suitable for tropical weather, sturdy walking shoes, a hat, and sunscreen are highly recommended, especially for the farm visit and outdoor historical sites. Clothes that can get wet for the elephant bathing are essential.
*   **Health & Safety:** Stay hydrated, especially during outdoor activities. Follow all instructions provided by the Ele Experience Farm staff for your safety and the well-being of the elephants.

---

### **Financial Parameter Acknowledgment:**

The estimated cost for the Ele Experience Farm visit, including entry and primary activities (elephant feeding, bathing, interaction), is **INR 2,500 - 4,000 per person**. This range allows for flexibility based on the specific package chosen and any additional offerings by the farm. Please be advised that this figure *excludes* all transportation costs, accommodation, meals, personal expenses, and entry fees for other attractions in Jaipur.

---

### **Detailed 2-Day Itinerary:**

---

#### **Day 1: Elephant Interaction & Amber Fort Grandeur**

*   **Morning Focus:** Ethical Elephant Experience
*   **Afternoon Focus:** Historical Fort Exploration

| Time Slot       | Activity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Logistical Notes & Financial Relevance                                                                                                                                                                                                                                 |
| :-------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **08:00 - 08:30** | **Breakfast** at your hotel.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Start the day energized. (Cost: Excluded)                                                                                                                                                                                                                              |
| **08:30 - 09:15** | **Travel to Ele Experience Farm:** Depart from your hotel in Jaipur city towards the farm, located near Amber Fort area.                                                                                                                                                                                                                                                                                                                                                                             | Approx. 30-45 min drive depending on traffic and hotel location. Ensure your pre-booked transport is ready. (Cost: Excluded, part of overall transport budget)                                                                                                          |
| **09:15 - 09:30** | **Arrival & Welcome at Ele Experience Farm:** Check-in, brief introduction to the farm's philosophy and the elephants.                                                                                                                                                                                                                                                                                                                                                                              | This is the starting point for your primary activity.                                                                                                                                                                                                                |
| **09:30 - 10:30** | **Elephant Feeding Session:** Engage in feeding the elephants with fruits and vegetables provided by the farm. Learn about their diet and individual personalities.                                                                                                                                                                                                                                                                                                                                  | A gentle and intimate way to bond with the elephants. (Cost: Included in the INR 2,500-4,000 farm fee)                                                                                                                                                                    |
| **10:30 - 12:00** | **Elephant Bathing & Interaction:** Participate in bathing the elephants (weather permitting) or enjoy a close-up interaction session, learning about their care and daily routines. Opportunity for photography.                                                                                                                                                                                                                                                                                       | Wear clothes you don't mind getting wet. This is often a highlight for visitors. (Cost: Included in the INR 2,500-4,000 farm fee)                                                                                                                                        |
| **12:00 - 12:45** | **Relaxation & Departure Prep:** Enjoy a complimentary refreshment (if offered), take last photos, and prepare for departure from the farm.                                                                                                                                                                                                                                                                                                                                                       | Reflect on your experience. Restrooms available.                                                                                                                                                                                                                     |
| **12:45 - 13:30** | **Lunch:** Enjoy a meal at a local restaurant near Amber Fort or head back towards the city for dining options.                                                                                                                                                                                                                                                                                                                                                                                      | Many options available, from traditional Rajasthani thalis to multi-cuisine. (Cost: Excluded)                                                                                                                                                                             |
| **13:30 - 16:30** | **Amber Fort Exploration:** Visit the magnificent Amber Fort, a UNESCO World Heritage Site. Explore its palaces, courtyards, and temples, including the Sheesh Mahal (Mirror Palace). You can take an electric jeep up to the fort entrance (elephant rides often have ethical concerns, and are not recommended).                                                                                                                                                                                        | Allow ample time (2-3 hours) for exploring the vast fort complex. Hire an authorized guide at the entrance for richer insights. (Cost: Entry fee ~INR 500/person for foreigners, ~INR 100/person for Indians; Guide fees extra; Electric jeep ~INR 150-200/person. Excluded) |
| **16:30 - 17:00** | **Visit Panna Meena ka Kund (Stepwell):** A short stop at the beautiful ancient stepwell located near Amber Fort.                                                                                                                                                                                                                                                                                                                                                                                      | Great photo opportunity. No entry fee.                                                                                                                                                                                                                                   |
| **17:00 - 18:00** | **Return to Hotel:** Travel back to your hotel in Jaipur city.                                                                                                                                                                                                                                                                                                                                                                                                                                     | Rest and freshen up after a busy day. (Cost: Excluded, part of overall transport budget)                                                                                                                                                                             |
| **18:00 - 20:00** | **Leisure / Evening Activity (Optional):** Relax or consider a visit to a local market for some early evening shopping.                                                                                                                                                                                                                                                                                                                                                                             | Flexibility to unwind.                                                                                                                                                                                                                                               |
| **20:00 onwards** | **Dinner:** Enjoy dinner at a recommended local restaurant, perhaps sampling traditional Rajasthani cuisine like Laal Maas or Dal Bati Churma.                                                                                                                                                                                                                                                                                                                                                      | Jaipur offers a wide range of dining experiences. (Cost: Excluded)                                                                                                                                                                                                     |

---

#### **Day 2: Jaipur City Heritage & Departure**

*   **Morning Focus:** Central Jaipur Royal Grandeur
*   **Afternoon Focus:** Shopping & Departure Preparation

| Time Slot       | Activity                                                                                                                                                                                                                                                                                                                                                                                            | Logistical Notes & Financial Relevance                                                                                                                                                                                                                                                                                                                               |
| :-------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **08:00 - 08:30** | **Breakfast** at your hotel.                                                                                                                                                                                                                                                                                                                                                                    | (Cost: Excluded)                                                                                                                                                                                                                                                                                                                                     |
| **08:30 - 09:00** | **Travel to Hawa Mahal:** Depart from your hotel for the iconic 'Palace of Winds'.                                                                                                                                                                                                                                                                                                               | (Cost: Excluded, part of overall transport budget)                                                                                                                                                                                                                                                                                                   |
| **09:00 - 09:30** | **Hawa Mahal (Palace of Winds):** Photo stop and brief appreciation of its unique architecture. View from outside for the best perspective.                                                                                                                                                                                                                                                        | A quick but essential stop. Entry inside is possible but less impactful than the exterior view. (Cost: No entry fee for exterior view; ~INR 50/person for interior for foreigners, ~INR 20/person for Indians - if you choose to enter. Excluded)                                                                                                |
| **09:30 - 12:30** | **City Palace & Jantar Mantar:** Explore the opulent City Palace complex, which houses museums, courtyards, and gardens. Adjacent to it, visit Jantar Mantar, an astronomical observatory.                                                                                                                                                                                                           | These two sites are next to each other, making for efficient exploration (2.5-3 hours combined). Consider a guide for Jantar Mantar to understand the instruments. (Cost: City Palace entry fee ~INR 700/person for foreigners, ~INR 200/person for Indians; Jantar Mantar entry fee ~INR 200/person for foreigners, ~INR 50/person for Indians. Excluded) |
| **12:30 - 13:30** | **Lunch:** Enjoy lunch at a restaurant in the vicinity of the city center.                                                                                                                                                                                                                                                                                                                       | Many options available. (Cost: Excluded)                                                                                                                                                                                                                                                                                                             |

In [34]:
!pip install streamlit
import streamlit as st
import pandas as pd
from google import genai
# Import your other required libraries (spacy, vaderSentiment, etc.) here

# --- Page Configuration ---
st.set_page_config(page_title="AI Itinerary Generator", layout="centered")
st.title("🌍 Smart Travel Itinerary Generator")
st.write("Enter your preferences below to generate a custom travel plan.")

# --- API Configuration ---
# In Streamlit, it is best practice to store secrets in a .streamlit/secrets.toml file
# For local testing, you can input it via the UI or securely load it.
api_key = st.text_input("Enter your Google Gemini API Key:", type="password")

# --- User Inputs (Frontend UI) ---
# Replacing your standard input() with Streamlit widgets
col1, col2 = st.columns(2)
with col1:
    preferred_city = st.text_input("Preferred Region/State (e.g., Kerala):", "")
with col2:
    attributes = st.text_input("What are you looking for? (e.g., history, nature):", "")

num_days = st.number_input("Duration of the trip (in days):", min_value=1, max_value=30, value=3)

# --- Execution Trigger ---
if st.button("Generate Itinerary"):
    if not api_key:
        st.error("Please provide a valid API key to proceed.")
    else:
        with st.spinner("Analyzing reviews and finding the best destination..."):
            try:
                # 1. Initialize the Client
                client = genai.Client(api_key=api_key)
                
                # ---------------------------------------------------------
                # INSERT YOUR NLP LOGIC HERE
                # (The Spacy and VADER analysis to generate 'filt_text')
                # For this example, I will mock the result of your NLP analysis
                # ---------------------------------------------------------
                
                # Mocking the result of your NLP engine:
                chosen_place = "Amber Fort" 
                chosen_city = "Jaipur"
                
                st.success(f"Algorithmically Selected Destination: **{chosen_place} in {chosen_city}**")
                
                # 2. Financial Estimation
                st.write(f"Calculating financial estimates for {chosen_place}...")
                est_prompt = f"Provide a concise financial estimate for a visit to {chosen_place} in {chosen_city}."
                est_response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=est_prompt
                )
                estimated_price = est_response.text
                
                # 3. Itinerary Generation
                st.write("Synthesizing your chronological itinerary...")
                itin_prompt = (
                    f"Act as a professional logistical coordinator. "
                    f"Formulate a structured {num_days}-day itinerary for a field expedition to {chosen_place} located in {chosen_city}. "
                    f"Integrate the primary activities, strategic time allocations, and accommodate a financial parameter of: {estimated_price}."
                )
                itin_response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=itin_prompt
                )
                
                # --- Final Output ---
                st.subheader("Your Custom Itinerary")
                st.markdown(itin_response.text) # Render the markdown response nicely
                
            except Exception as e:
                st.error(f"An error occurred during execution: {e}")

Requirement already satisfied: streamlit in c:\users\cheta\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\cheta\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\cheta\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\cheta\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\cheta\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\cheta\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\cheta\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\cheta\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cheta\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cheta\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cheta\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cheta\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: attrs>=22.2.0 in c:\users\cheta\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\cheta\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\cheta\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\cheta\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\cheta\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\cheta\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)

2026-04-01 11:24:39.653 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:39.658 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.419
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\cheta\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-04-01 11:24:40.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.451 Session state does not function when running a script without `streamlit run`
2026-04-01 11:24:40.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.467 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.512 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.519 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.531 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 11:24:40.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.